#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${1:-$(cd "$(dirname "$0")/.." && pwd)}"

required_files=(
  "config/framework.yaml.example"
  "agents/orchestrator.md"
  "agents/spec.md"
  "agents/security.md"
  "agents/release-manager.md"
  "agents/builder.md"
  "agents/qa.md"
  "policies/repo-management.md"
  "docs/delivery/repo-management-operating-model.md"
  "deploy/manifest.yaml"
  "scripts/set-agent-git-identity.sh"
  "scripts/create-agent-issue.sh"
  "scripts/create-agent-pr.sh"
  "scripts/update-agent-pr-body.sh"
  "scripts/update-agent-wiki-page.sh"
  "scripts/post-pr-line-comment.sh"
  "scripts/post-bug-report.sh"
  "scripts/check-framework-version.sh"
  "scripts/check-task-ledger-overdue.py"
  "scripts/validate-agent-artifacts.py"
  "scripts/validate-callback.py"
  "scripts/validate-qa-scope.py"
  "scripts/validate-issue-ready.py"
  "scripts/update-task-ledger.py"
  "scripts/update-release-state.py"
  "scripts/validate-release-state.py"
  "scripts/check-release-issues.sh"
  "scripts/generate-release-notes.sh"
  "scripts/cut-release-tag.sh"
  "scripts/validate-task-ledger.py"
  "scripts/validate-decision-record.py"
  "scripts/validate-readme-contract.sh"
  "scripts/validate-docker-first-project.sh"
  "scripts/validate-project-bootstrap.sh"
  "scripts/validate-config.sh"
  "scripts/dispatch-named-agent.sh"
  "scripts/send-agent-callback.sh"
  "scripts/sync-agent-repo.sh"
  "scripts/prepare-specialist-spawn.py"
  "scripts/onboard-project.sh"
  "scripts/validate-specialist-template.py"
  "scripts/validate-workflows.py"
  "templates/callback-report.md"
  "templates/bug-report.md"
  "templates/decision-record.md"
  "templates/swarm-smoke-test.md"
  "templates/swarm-behavior-test/orchestrator.md"
  "templates/swarm-behavior-test/spec.md"
  "templates/swarm-behavior-test/builder.md"
  "templates/swarm-behavior-test/qa.md"
  "templates/swarm-behavior-test/security.md"
  "templates/swarm-behavior-test/release-manager.md"
  "schemas/callback.md"
  "schemas/decision-record.md"
  "schemas/specialist-template.md"
  "schemas/workflow.json"
  "docs/delivery/task-ledger.md"
  "docs/delivery/openclaw-cron-watchdog.md"
  "docs/delivery/release-manager-operating-model.md"
  "docs/delivery/orchestrator-tooling-helpers.md"
  "docs/delivery/release-manager-tooling-helpers.md"
  "docs/agents/README.md"
  "docs/agents/orchestrator.md"
  "docs/agents/spec.md"
  "docs/agents/spec-architect.md"
  "docs/agents/security.md"
  "docs/agents/release-manager.md"
  "docs/agents/builder.md"
  "docs/agents/qa.md"
  "docs/decisions/.gitkeep"
  "agents/specialists/typescript-engineer.md"
  "agents/specialists/python-engineer.md"
  "agents/specialists/frontend-ui.md"
  "agents/specialists/backend-integration.md"
  "agents/specialists/api-design.md"
  "agents/specialists/database-migration.md"
  "agents/specialists/test-harness.md"
  "agents/specialists/test-suite-builder.md"
  "agents/specialists/ci-container.md"
  "agents/specialists/library-evaluation.md"
  "agents/specialists/technical-option-comparison.md"
  "agents/specialists/architecture-research.md"
  "agents/specialists/migration-scoping.md"
  "agents/specialists/qa-regression.md"
  "agents/specialists/qa-edge-case.md"
  "agents/specialists/qa-accessibility.md"
  "agents/specialists/qa-security.md"
  "agents/specialists/qa-docs-verification.md"
  "agents/specialists/ux-designer.md"
  "agents/specialists/visual-designer.md"
  "agents/specialists/usability-reviewer.md"
  "agents/specialists/docker-environment.md"
  "agents/specialists/aws-infrastructure.md"
  "agents/specialists/gcp-infrastructure.md"
  "agents/specialists/azure-infrastructure.md"
  "agents/specialists/terraform-core.md"
  "agents/specialists/cicd-architect.md"
  "agents/specialists/aws-architect.md"
  "agents/specialists/gcp-architect.md"
  "agents/specialists/azure-architect.md"
  "agents/specialists/threat-modeller.md"
  "agents/specialists/dependency-auditor.md"
  "policies/spec-process.md"
  "workflows/implement-feature.yaml"
  "workflows/fix-bug.yaml"
  "workflows/prepare-release.yaml"
  "repo-templates/.github/pull_request_template.md"
  "repo-templates/.github/ISSUE_TEMPLATE/release-tracking.md"
  "repo-templates/.github/workflows/merge-gate.yml"
  "repo-templates/README.md"
  "repo-templates/docs/delivery/release-state.md"
  "repo-templates/docs/delivery/task-ledger.md"
  "repo-templates/SPEC.md"
)

for rel in "${required_files[@]}"; do
  if [ ! -f "$ROOT_DIR/$rel" ]; then
    echo "ERROR: missing required file: $rel" >&2
    exit 1
  fi
done

required_exec=(
  "deploy/sync-framework.sh"
  "scripts/validate-config.sh"
  "scripts/validate-docker-first-project.sh"
  "scripts/validate-project-bootstrap.sh"
  "scripts/set-agent-git-identity.sh"
  "scripts/create-agent-issue.sh"
  "scripts/create-agent-pr.sh"
  "scripts/update-agent-pr-body.sh"
  "scripts/update-agent-wiki-page.sh"
  "scripts/post-agent-comment.sh"
  "scripts/post-pr-line-comment.sh"
  "scripts/post-bug-report.sh"
  "scripts/check-framework-version.sh"
  "scripts/check-task-ledger-overdue.py"
  "scripts/render-agent-comment.py"
  "scripts/render-agent-pr-body.py"
  "scripts/render-agent-wiki-page.py"
  "scripts/validate-agent-artifacts.py"
  "scripts/lint-agent-markdown.py"
  "scripts/validate-callback.py"
  "scripts/validate-qa-scope.py"
  "scripts/validate-issue-ready.py"
  "scripts/update-task-ledger.py"
  "scripts/update-release-state.py"
  "scripts/validate-task-ledger.py"
  "scripts/validate-release-state.py"
  "scripts/check-release-issues.sh"
  "scripts/generate-release-notes.sh"
  "scripts/cut-release-tag.sh"
  "scripts/validate-decision-record.py"
  "scripts/validate-readme-contract.sh"
  "scripts/dispatch-named-agent.sh"
  "scripts/send-agent-callback.sh"
  "scripts/prepare-specialist-spawn.py"
  "scripts/onboard-project.sh"
  "scripts/validate-specialist-template.py"
  "scripts/validate-workflows.py"
  "scripts/smoke-test-agent-swarm.sh"
  "scripts/smoke-test-workflow.sh"
  "scripts/validate-agent-workspace-layout.sh"
  "scripts/clone-agent-project-repo.sh"
  "scripts/sync-agent-repo.sh"
  "scripts/scaffold-project-repo.sh"
  "scripts/install-project-watchdog.sh"
  "scripts/prime-named-agent-sessions.sh"
)

for rel in "${required_exec[@]}"; do
  if [ ! -x "$ROOT_DIR/$rel" ]; then
    echo "ERROR: required executable is missing or not executable: $rel" >&2
    exit 1
  fi
done

"$ROOT_DIR/scripts/validate-config.sh" --file "$ROOT_DIR/config/framework.yaml.example"

"$ROOT_DIR/scripts/validate-task-ledger.py" "$ROOT_DIR/docs/delivery/task-ledger.md"
"$ROOT_DIR/scripts/validate-release-state.py" "$ROOT_DIR/repo-templates/docs/delivery/release-state.md"
"$ROOT_DIR/scripts/validate-decision-record.py" "$ROOT_DIR/templates/decision-record.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/typescript-engineer.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/python-engineer.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/frontend-ui.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/backend-integration.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/api-design.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/database-migration.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/test-harness.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/test-suite-builder.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/ci-container.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/library-evaluation.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/technical-option-comparison.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/architecture-research.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/migration-scoping.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/qa-regression.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/qa-edge-case.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/qa-accessibility.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/qa-security.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/qa-docs-verification.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/ux-designer.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/visual-designer.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/usability-reviewer.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/docker-environment.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/aws-infrastructure.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/gcp-infrastructure.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/azure-infrastructure.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/terraform-core.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/cicd-architect.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/aws-architect.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/gcp-architect.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/azure-architect.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/threat-modeller.md"
"$ROOT_DIR/scripts/validate-specialist-template.py" "$ROOT_DIR/agents/specialists/dependency-auditor.md"
"$ROOT_DIR/scripts/validate-workflows.py" "$ROOT_DIR/workflows/implement-feature.yaml" "$ROOT_DIR/workflows/fix-bug.yaml" "$ROOT_DIR/workflows/prepare-release.yaml"

echo "Framework validation passed for $ROOT_DIR"
